language: java
jdk:
  - openjdk11

branches:
  only:
    - master

before_install:
  - cd SouP/
  - chmod +x gradlew

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - sis000512@naver.com