aws:
  paramstore:
    enabled: true
    prefix: /spring-boot-aws
    name: cloud-parameter-store
    profileSeparator: _
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: WARN
